control_msgs:
  fails:
    backup:                     "{{ control_name }}.FAIL__На сервере запущен процесс снятия резервной копии данных. Выполнение операции невозможно до завершения__{{ control_name }}.FAIL"
    lag:                        "{{ control_name }}.FAIL__На сервере присутствует задержка репликации данных с мастера на реплику. Обратитесь к администраторам БД__{{ control_name }}.FAIL"
    maintenance_mode:           "{{ control_name }}.FAIL__На севере включен режим обслуживания patroni. Обратитесь к администраторам БД__{{ control_name }}.FAIL"
    unexpected:                 "{{ control_name }}.FAIL__Произошла неожиданная ошибка. Обратитесь к администраторам {{ control_name }}__{{ control_name }}.FAIL"
    db_pgse_stopped:            "{{ control_name }}.FAIL__База данных не запущена на сервере. Обратитесь к администраторам БД__{{ control_name }}.FAIL"
    patroni_stopped:            "{{ control_name }}.FAIL__Patroni не запущен на сервере. Обратитесь к администраторам БД__{{ control_name }}.FAIL"
    db_pgse_started:            "{{ control_name }}.FAIL__База данных уже запущена на сервере__{{ control_name }}.FAIL"
    patroni_started:            "{{ control_name }}.FAIL__Patroni уже запущен на сервере__{{ control_name }}.FAIL"
    json_not_exists:            "{{ control_name }}.FAIL__Выбранные для запуска сервера были остановлены без использования {{ control_name }}. Запуск возможно выполнить только вручную.__{{ control_name }}.FAIL"
    rlm_data_not_exists:        "{{ control_name }}.FAIL__Отсутствует обязательный входной параметр rlm_data. Обратитесь к администраторам {{ control_name }}__{{ control_name }}.FAIL"
    scenario:                   "{{ control_name }}.FAIL__Сценарий завершился с ошибкой. Обратитесь к администраторам {{ control_name }}__{{ control_name }}.FAIL"
    unlock_user:                "{{ control_name }}.FAIL__Ошибка во время разблокировки пользователя user_name_and_msg__{{ control_name }}.FAIL"
    reset_user_password:        "{{ control_name }}.FAIL__Ошибка во время смены пароля для пользователя user_name_and_msg__{{ control_name }}.FAIL"
    create_user_exist:          "{{ control_name }}.FAIL__Создание УЗ пользователя БД не возможно. УЗ пользователя существует в БД__{{ control_name }}.FAIL"
    role_type:                  "{{ control_name }}.FAIL__Создание УЗ пользователя БД не возможно. Неизвестный тип УЗ пользователя__{{ control_name }}.FAIL"
    create_user_error:          "{{ control_name }}.FAIL__Ошибка во время создания новой УЗ пользователя БД: _msg__{{ control_name }}.FAIL"
    ext_schema_does_not_exist:  "{{ control_name }}.FAIL__В базе данных не создана схема ext.Создайте ее самостоятельно или обновите версию базы данных__{{ control_name }}.FAIL"
    sch_or_ext_is_not_defined:  "{{ control_name }}.FAIL__Перед запуском сценария не переданы параметры selected_schemas или selected_database__{{ control_name }}.FAIL"
    not_exist_pgbouncer:        "{{ control_name }}.FAIL__На сервере отсутсвует pgBouncer__{{ control_name }}.FAIL"
    stopped_pgbouncer:          "{{ control_name }}.FAIL__На сервере остановлен pgBouncer__{{ control_name }}.FAIL"
    differ_pgbouncer:           "{{ control_name }}.FAIL__На мастере и на реплике разные значения для параметров. \
                                 Для выполнения сценария необходимо синхронизировать значения параметров__{{ control_name }}.FAIL"
    validation_error:           "{{ control_name }}.FAIL__Введенное вами значение параметра _param_name не прошло валидацию.\ 
                                 Выберите значение из списка _list_params и перезапустите сценарий__{{ control_name }}.FAIL"
    fail_tunning:              "{{ control_name }}.FAIL__При применении новых параметров произошла ошибка__{{ control_name }}.FAIL"
    backup_fail:               "{{ control_name }}.FAIL__Бэкап файл для pgbouncer не был создан__{{ control_name }}.FAIL"
    password_encryption_fail:  "{{ control_name }}.FAIL__Данный сценарий не доступен, т.к. значение параметра password_encryption отличается от значения требуемого по ВНД 4736. \
                                Рекомендуем обратиться к администраторам СУБД и изменить значение на scram-sha-256, либо предварительно обновить версию СУБД Pangolin на 4.5.0 и выше__{{ control_name }}.FAIL"
  ok:
    switchover:                 "{{ control_name }}.OK__Переключение ролей узлов в кластере PostgreSQL SE успешно выполнено__{{ control_name }}.OK"
    stop_database:              "{{ control_name }}.OK__База данных на выбранных серверах успешно остановлена__{{ control_name }}.OK"
    start_database:             "{{ control_name }}.OK__База данных на выбранных серверах успешно запущена__{{ control_name }}.OK"
    scouting_users:             "{{ control_name }}.OK__Разведка пользователей успешно выполнена__{{ control_name }}.OK"
    unlock_reset_user:          "{{ control_name }}.OK__Разблокировка УЗ и сброс паролей успешно выполнены__{{ control_name }}.OK"
    create_user:                "{{ control_name }}.OK__Создание УЗ пользователя БД успешно выполнено__{{ control_name }}.OK"
    create_user_ldap:           "{{ control_name }}.OK__Создание УЗ пользователя БД для аутентификации через LDAP успешно выполнено__{{ control_name }}.OK"
    scouting_pgbouncer:         "{{ control_name }}.OK__Разведка параметров pgBouncer успешно выполнена__{{ control_name }}.OK"
    tunning_pgbouncer:          "{{ control_name }}.OK__Изменение параметров pgBouncer успешно выполнено__{{ control_name }}.OK"
    scout_edit_pg_hba:          "{{ control_name }}.OK__Разведка перед правкой раздела pg_hba успешно выполнена__{{ control_name }}.OK"
    edit_pg_hba:                "{{ control_name }}.OK__Правка раздела pg_hba успешно выполнена, изменения вступили в силу__{{ control_name }}.OK"
control_files:
  tmp_dir: '{{ PGUSERHOME }}/.rlm'
  json_file: 'nodes.json'
control_error_flag: false
contrib_extensions:
  pg_catalog: ['adminpack', 'plpgsql','pltcl', 'pltclu', 'plperlu', 'plperl', 'plpythonu', 'plpython2u', 'plpython3u']
  not_install_automated: ['pg_cron', 'timescaledb', 'ltree_plpython3u', 'jsonb_plpython3u', 'hstore_plpython3u']
default_recommend_base_db: "{{ pg_max_connections|int - pg_coef_conns }}"
scenario_error: false
scenario_error_not_exist: false
scenario_error_stopped: false
scenario_error_differ: false
with_confd: False 
pgbouncer_parameters:
  list_pgbouncer_params: [ 'max_client_conn', 'pool_mode', 'default_pool_size','max_db_connections', 'max_user_connections']
  need_recommend:
    max_client_conn: "1,{{ processor_vcpus*100 }}"
    default_pool_size: "1,{{ default_recommend_base_db }}"
    max_db_connections: "1,{{ default_recommend_base_db }}"
    max_user_connections: "1,{{ default_recommend_base_db }}"
    pool_mode: " "
  default_value:
    max_client_conn: "{{ processor_vcpus*100 }}"
    default_pool_size: "{{ default_recommend_base_db }}"
    max_db_connections: "{{ default_recommend_base_db }}"
    max_user_connections: "{{ default_recommend_base_db }}"
    pool_mode: "transaction"
  default_community_value:
    max_client_conn: 100
    default_pool_size: 20
    max_db_connections: 0
    max_user_connections: 0
    pool_mode: "session"  
  need_valid: {'pool_mode':['transaction','session','statement']}
control_edit_pg_hba:
  allowed_type_conn: ['host']
  allowed_db: ['all']
  allowed_users: ['+as_TUZ']
  allowed_conn_settings: ['scram-sha-256','md5']
  allowed_bits: [ '0', '12', '16', '24', '32']
  disallowed_ips: []
edited_pg_hba_strings: ['']