legal_extensions:
  third_party: "'pg_profile', 'orafce', 'postgis', 'pgrouting', 'pg_squeeze', 'pg_cron', 'pg_pathman', 'pg_repack', 'pgse_backup', 'pg_hint_plan', \
                'pg_outline', 'oracle_fdw', 'tds_fdw', 'psql_lockmon', 'pg_stat_kcache'"
  contrib: "'adminpack', 'amcheck', 'auth_delay', 'auto_explain', 'autoinc', 'bloom', 'btree_gin', 'btree_gist', 'citext', 'cube', 'dblink', 'dict_int', 'dict_xsyn', \
            'earthdistance', 'file_fdw', 'fuzzystrmatch', 'hstore', 'hstore_plperl', 'hstore_plperlu', 'hstore_plpython2u', 'hstore_plpython3u', 'hstore_plpythonu', \
            'insert_username', 'intagg', 'intarray', 'isn', 'jsonb_plperl', 'jsonb_plperlu', 'jsonb_plpython2u', 'jsonb_plpython3u', 'jsonb_plpythonu', 'lo', 'ltree', \
            'ltree_plpython2u', 'ltree_plpython3u', 'ltree_plpythonu', 'moddatetime', 'pageinspect', 'pg_buffercache', 'pg_freespacemap', 'pg_prewarm', 'pg_stat_statements', \
            'pg_trgm', 'pg_visibility', 'pgcrypto', 'pgrowlocks', 'pgstattuple', 'plperl', 'plperlu', 'plpgsql', 'plpython2u', 'plpythonu', 'pltcl', 'pltclu', 'postgres_fdw', \
            'refint', 'seg', 'sslinfo', 'tablefunc', 'tcn', 'timetravel', 'tsm_system_rows', 'tsm_system_time', 'unaccent', 'uuid-ossp', 'xml2', 'bool_plperlu', 'bool_plperl'"

scout_control_msgs:
  fails:
    max_worker_processes_small_value: "{{ control_name }}.FAIL__Минимально допустимое значение для max_worker_processess должно быть >= {{ max_used_worker_process }}. \
                                       Допущена ошибка в конфигурировании max_worker_processess.__{{ control_name }}.FAIL"
    duplicates_error: "{{ control_name }}.FAIL__В файле {{ patroni_files.conf_dir }}/postgres.yml найдены параметры, имеющие дубли. Необходимо проанализировать конфигурационный файл \
                       и выбрать необходимое значение, чтобы избежать ошибок при мерже конфигурационного файла и утери необходимого значения__{{ control_name }}.FAIL"
    user_not_decided_about_src_update: "{{ control_name }}.FAIL__В каталоге {{ manage_backup_bin }} найдены установочные файлы СРК, необходимо принять решение, \
                                        обновлять их совместно с СУБД или нет.__{{ control_name }}.FAIL"
    user_decided_src_update_but_src_not_installed: "{{ control_name }}.FAIL__Обновление СРК невозможно, ввиду отсутствия в каталоге {{ manage_backup_bin }} установочных файлов СРК.__{{ control_name }}.FAIL"
    user_decided_src_update_but_src_not_correct_installed: "{{ control_name }}.FAIL__Обновление СРК невозможно, ввиду некорректной предыдущей установки.__{{ control_name }}.FAIL"
    wrong_data_type:                  "{{ control_name }}.FAIL__Удалена поддержка типов данных abstime, reltime, tinterval. \
                                       Список таблиц, использующих их (<имя схемы>.<имя таблицы>(<имя колонки>)): table_name__{{ control_name }}.FAIL"
    unsupported_arrays_of_types:      "{{ control_name }}.FAIL__Не поддерживаются массивы типов из information_schema. \
                                       Список таблиц, использующих их (<имя схемы>.<имя таблицы>(<имя колонки>)): table_name__{{ control_name }}.FAIL"
    wrong_procedure_python2:          "{{ control_name }}.FAIL__Прекращена поддержка языка Python 2.х. \
                                       Список процедур, использующих их (<имя схемы>.<имя процедуры>): procedure_name__{{ control_name }}.FAIL"
    local_backup_path_is_not_exists:  "{{ control_name }}.FAIL__Не найден каталог local_backup_path_folder, указанный в параметре local_backup_path.__{{ control_name }}.FAIL"
    rpm_package_and_version_found:    "{{ control_name }}.FAIL__Найден установленный пакет package_name с версией на которую планируем обновляться. \
                                       Обновление не может быть продолжено. Просьба удалить пакет и повторить попытку снова.__{{ control_name }}.FAIL"
    scout_temp_data_path_is_exists:   "{{ control_name }}.FAIL__Найден каталог local_backup_path/scout_temp_data. Данный каталог нужен для временных файлов. \
                                        Просьба удалить данный каталог и повторить запуск.__{{ control_name }}.FAIL"
    upgrade_check_failed:             "{{ control_name }}.FAIL__Не прошла одна из проверок pg_upgrade. Обратитесь к администраторам БД для анализа проблемы. \
                                       С ошибками можно ознакомиться на хосте master в директории pg_scout_log_link \
                                       {% if is_print_pg_upgrade_logs %}\
                                       или в логе задачи (имя таски: journal pg_upgrade)\
                                       {% endif %}\
                                       .__{{ control_name }}.FAIL"
    unsupported_version_number:       "{{ control_name }}.FAIL__Обновление невозможно. Текущая версия (pg_current_version) не поддерживается. \
                                       Минимальная поддерживаемая версия: min_actual_pangolin_ver__{{ control_name }}.FAIL"
    missing_ext_pgse:                 "{{ control_name }}.FAIL__Текущая версия СУБД содержит следующие расширения, не входящие в состав Pangolin или для данных расширений \
                                       обновление не поддерживается (<имя базы>.<имя схемы>.<имя расширения>): extension_name.__{{ control_name }}.FAIL"
    not_support_type_installed_configuration: "{{ control_name }}.FAIL__Тип установленной конфигурации: tag. Процесс обновления для данного типа недоступен. \
                                               Предварительно необходимо привести тип конфигурации к одному из поддерживаемых типов (как за счет чистой установки \
                                               новой СУБД, так и за счет ручного изменения типа конфигурации)__{{ control_name }}.FAIL"
    update_file_exists:               "{{ control_name }}.FAIL__Зафиксирована неудачная попытка обновления версии СУБД Pangolin. Перед повторным перезапуском сценария \
                                       обновления, необходимо полностью восстановить состояние кластера предыдущей/исходной версии СУБД Pangolin. \
                                       Обратитесь к администраторам БД__{{ control_name }}.FAIL"
    trigger_update_file_exists:        "{{ control_name }}.FAIL__Зафиксирован принудительный откат пользователем СУБД Pangolin. Перед повторным перезапуском сценария \
                                       обновления требуется удалить файл {{ update_status_files.dir }}/.trigger_stop_update__{{ control_name }}.FAIL"
    failed_upload_schema_new_db:      "{{ control_name }}.FAIL__Найдены ошибки во время проверки загрузки схемы данных. Обратитесь к администраторам БД для анализа проблемы. \
                                       Ссылка на схему данных в папке с логами: (ansible_fqdn)pg_scout_log_link/currentdb.sql. Список ошибок: list_errors. \
                                       Если после анализа выявлено, что ошибка ложно положительная, то необходимо добавить эту ошибку в фильтр в переменную \
                                       false_error_filter_for_data_schema кастомного конфигурационного файла.__{{ control_name }}.FAIL"
    no_supported_version_found:       "{{ control_name }}.FAIL__Обновление невозможно. Текущая версия (pg_current_version) не найдена в доступных к обновлению.__{{ control_name }}.FAIL"
    no_supported_new_version:         "{{ control_name }}.FAIL__Обновление невозможно. Версия, на которую производится попытка обновления, не поддерживается.__{{ control_name }}.FAIL"
    unsupported_version:              "{{ control_name }}.FAIL__Обновление невозможно. При включенной функциональности прозрачного шифрование данных (TDE)/\
                                       защиты от привилегированных пользователей (AP) обновление в автоматическом режиме не поддерживается для \
                                       версии (pg_current_version). Обратитесь к администраторам СУБД для осуществления обновления вручную.__{{ control_name }}.FAIL"
    pg_upgrade_mode_not_exists:       "{{ control_name }}.FAIL__Обновление невозможно. Отсутствует значение для параметра pg_upgrade_mode.__{{ control_name }}.FAIL"
    unexpected:                       "{{ control_name }}.FAIL__В процессе работы скрипта разведки произошла неожиданная ошибка. Обратитесь к администраторам \
                                       БД для анализа проблемы.__{{ control_name }}.FAIL"
    incorrect_repo:                   "{{ control_name }}.FAIL__Обнаружена ошибка во время проверки скачивания {{ ansible_pkg_mgr.split('_').0 }} пакетов {{ error_list }}. \
                                       Проверьте доступность репозиториев указанных в кастомном конфиге.__{{ control_name }}.FAIL"
    unexpected_upload_schema_new_db:  "{{ control_name }}.FAIL__Произошла неожиданная ошибка во время проверки загрузки схемы данных. \
                                       Обратитесь к администраторам БД для анализа проблемы. Список ошибок: list_errors.__{{ control_name }}.FAIL"
    unexpected_start_new_db:          "{{ control_name }}.FAIL__Произошла неожиданная ошибка во время старта СУБД для проверки загрузки схемы данных. \
                                       Обратитесь к администраторам БД для анализа проблемы. Список ошибок: list_errors.__{{ control_name }}.FAIL"
    incorrect_pgdata_location:        "{{ control_name }}.FAIL__В кандидате на обновление обнаружено некорректное расположение PGDATA. \
                                       Сейчас - pgdata_real. Должно быть - pgdata_should_be__{{ control_name }}.FAIL"
    manage_backup_sh_is_not_exists:   "{{ control_name }}.FAIL__Файл manage_backup.sh не существует. Обратитесь к администраторам БД__{{ control_name }}.FAIL"
    backup_user_doesnt_exists:        "{{ control_name }}.FAIL__Техническая учетная запись backup_user не используется в процессе резервного копирования. \
                                       Обратитесь к администраторам БД__{{ control_name }}.FAIL"
    different_type_of_file_system:    "{{ control_name }}.FAIL__Для продолжения обновления необходимо, чтобы директории с текущей pgdata, новой pgdata, pgbackup и local_backup_path \
                                       находились в одной файловой системе. Тип файловой системы: текущая pgdata: pgdata_old_file_system_type, новая pgdata: pgdata_file_system_type, \
                                       pgbackup: pgbackup_file_system_type, local_backup_path: local_backup_path_file_system_type.__{{ control_name }}.FAIL"
    incorrect_pgdata_directory_structure: "{{ control_name }}.FAIL__Разная структура каталогов в каталоге pgdata на серверах. Обратитесь к администраторам БД для анализа проблемы. \
                                           Со структурой можно ознакомиться в логе задачи (имя таски: pgdata directory structure).__{{ control_name }}.FAIL"
    symlinks_pgdata_different:        "{{ control_name }}.FAIL__Отличаются символические ссылки в каталоге pgdata на серверах. Обратитесь к администраторам БД для анализа проблемы. \
                                       Со списком символических ссылок можно ознакомиться в логе задачи (имя таски: symlinks in pgdata).__{{ control_name }}.FAIL"
    maximum_dbms_size_to_update:      "{{ control_name }}.FAIL__Автоматическое обновление ограничено размером кластера СУБД в maximum_dbms_size_to_update Гб. \
                                       Текущая СУБД имеет размер current_dbms_size Гб.__{{ control_name }}.FAIL"
    new_pgdata_is_exists:             "{{ control_name }}.FAIL__Директория {{ PGDATA.split('/')[:-1] | join('/') }}, в которую будут переноситься данные после процесса миграции уже существует. \
                                       Требуется удалить данную директорию для дальнейшего обновления__{{ control_name }}.FAIL"
    new_pgbackup_is_exists:           "{{ control_name }}.FAIL__Директория {{ PGBACKUP }}, в которой будут созданы бэкапы обновляемой базы данных уже существует. \
                                       Требуется удалить либо переименовать данную директорию для дальнейшего обновления__{{ control_name }}.FAIL"
    new_pgdata_link_is_exists:        "{{ control_name }}.FAIL__Директория /pgdata/{{ pg_major_version }}, которая будут использоваться после обновления уже существует. \
                                       Требуется удалить либо переименовать данную директорию для дальнейшего обновления__{{ control_name }}.FAIL"
    new_pgbackup_link_is_exists:      "{{ control_name }}.FAIL__Директория {{ PGBACKUP.split('/').1 }}/{{ pg_major_version }}, которая будут использоваться после обновления уже существует. \
                                       Требуется удалить либо переименовать данную директорию для дальнейшего обновления__{{ control_name }}.FAIL"
    no_free_space_in_pgdata_on_replica: "{{ control_name }}.FAIL__Не достаточно свободного места в точке монтирования для pgdata на реплике (current_replica) для выполнения обновления. 
                                         Доступно свободного места pgdata_mp_free_mb Мб, требуется pgdata_size_mb_x2 Мб__{{ control_name }}.FAIL"
    pg_auth_config_check:             "{{ control_name }}.FAIL__Не прошла проверка доступа к БД с использованием зашифрованного хранилища паролей (pg_auth_config check). \
                                       Обратитесь к Администраторам СУБД.__{{ control_name }}.FAIL"
    pg_stat_statements_all_base:      "{{ control_name }}.FAIL__Расширение pg_stat_statements установлено не во всех бд, для дальнейшего обновления требуется \
                                        установить расширение в следующую бд database_name.__{{ control_name }}.FAIL"
    pg_hint_plan_all_base:            "{{ control_name }}.FAIL__Расширение pg_hint_plan установлено не во всех бд, для дальнейшего обновления требуется \
                                            установить расширение в следующую бд database_name.__{{ control_name }}.FAIL"
  fail_space:
    local_backup_path_no_free_space:  "{{ control_name }}.SPACE.FAIL__Не достаточно свободного места для локального бэкапа в local_backup_path_folder. \
                                       Доступно local_backup_path_free_mb Мб. Требуется >= local_size_backup_mb Мб.__{{ control_name }}.SPACE.FAIL"
    disk_pgbackup_min:                "{{ control_name }}.FAIL__Точка монтирования {{ PGBACKUP }} имеет {} Гб свободного пространства, но требуется не менее 1 Гб.__{{ control_name }}.FAIL"
  warnings:
    src_defined_and_user_not_decided_update:    "{{ control_name }}.WARNING__В каталоге {{ manage_backup_bin }} найдены установочные файлы СРК. Вы уверены, что не хотите обновить их \
                                      совместно с обновлением СУБД? В противном случае, служба СРК после обновления не сможет создавать РК в процессе своей работы.__{{ control_name }}.WARNING"
    wrong_extension:                  "{{ control_name }}.WARNING__Установка расширений в схему public или в системный каталог противоречит ВНД. \
                                       Список расширений, установленных в них (<имя схемы>.<имя расширения>): extension_name__{{ control_name }}.WARNING"
    wrong_ext_pgse:                   "{{ control_name }}.WARNING__Текущая версия СУБД содержит следующие расширения, не входящие в состав Pangolin \
                                       (<имя базы>.<имя схемы>.<имя расширения>): extension_name. Для дальнейшей работы данных расширений \
                                       необходимо после обновления проверить их работоспособность.__{{ control_name }}.WARNING"
    pgport_new_old_not_equal:         "{{ control_name }}.WARNING__В кандидате на обновление обнаружено использование старого порта PGPORT = pgport_old, нерекомендуемого \
                                       безопасностью.__{{ control_name }}.WARNING"
    pgbouncer_new_old_not_equal:      "{{ control_name }}.WARNING__В кандидате на обновление обнаружено использование старого pgbouncer порта pgbouncerport_old, нерекомендуемого \
                                       безопасностью.__{{ control_name }}.WARNING"
    haproxy_new_old_not_equal:        "{{ control_name }}.WARNING__В кандидате на обновление обнаружено использование старого haproxy порта haproxyport_old, нерекомендуемого \
                                       безопасностью.__{{ control_name }}.WARNING"
    confd_exists:                     "{{ control_name }}.WARNING__В случае использования конфигурации СУБД cluster-patroni-etcd-pgbouncer (версии СУБД Pangolin до 5.1.0) \
                                       при мажорном обновлении, утилита confd будет автоматически удалена.  Поэтому до обновления необходимо изменить строку подключения \
                                       к СУБД (проверить значения портов) и убедиться что в строке указаны обе ноды кластера (лидер и реплика). Например, если раньше было \
                                       «jdbc:postgresql://127.0.0.1:6544,127.0.0.2:6544/dbname?prepareThreshold=0», то необходимо исправить на «jdbc:postgresql://127.0.0.1\
                                       :6544,127.0.0.2:6544/dbname?targetServerType=master&prepareThreshold=0»__{{ control_name }}.WARNING"
    data_public:                      "{{ control_name }}.WARNING__Данные в схеме public существуют, что противоречит ВНД. \
                                       Список таблиц (<имя базы>.<имя схемы>.<имя таблицы>: table_name__{{ control_name }}.WARNING"
    ldap_tls:                         "{{ control_name }}.WARNING__Параметр шифрования ldap соединения 'ldaptls=1' не был обнаружен в pg_hba.conf.\
                                        Шифрование ldap-соединения выключено.__{{ control_name }}.WARNING"
    role_model:                       "{{ control_name }}.WARNING__Ролевая модель не будет обновлена для групп '{{ db_admin }}', '{{ as_group }}', '{{ TUZ_group }}'.__{{ control_name }}.WARNING"
    rsyslog:                          "{{ control_name }}.WARNING__Служба RSYSLOG выключена или не установлена. Настройка службы будет произведена.__{{ control_name }}.WARNING"
    md5_rules:                        "{{ control_name }}.WARNING__В файле pg_hba были обнаружены правила, содержащие метод аутентификации 'md5': scout_md5_rules__{{ control_name }}.WARNING"
  args:
    args_parameters:                  "{{ control_name }}.ARGS__args_parameters__{{ control_name }}.ARGS"
  info:
    not_hard_link:                    "{{ control_name }}.INFO__Для миграции данных БД используется специальная утилита pg_upgrade. В ходе миграции данные в новую версию БД \
                                       будут перенесены в режиме копирования, что повлечет дополнительное увеличение времени обновления СУБД.__{{ control_name }}.INFO"
    dbms_is_not_available:            "{{ control_name }}.INFO__СУБД будет недоступно на протяжении всего процесса обновления.__{{ control_name }}.INFO"
    third_party_backup:               "{{ control_name }}.INFO__За процедуру резервного копирования данных, на случай непредвиденных ошибок \
                                       в процессе обновления, отвечает отдельная от Механизма обновления служба.__{{ control_name }}.INFO"
    remove_trigger_file:              "{{ control_name }}.INFO__Был найден и удален триггер прерывания обновления.__{{ control_name }}.INFO"
    remove_disallow_update_file:      "{{ control_name }}.INFO__Был найден и удален файл предыдущего неудачного обновления.__{{ control_name }}.INFO"
  ok:
    scout_successfully:               "{{ control_name }}.OK__Разведка перед обновлением успешно выполнена.__{{ control_name }}.OK"
  todo_after:
    actions_after_major_update:       "{{ control_name }}.TODO.AFTER__Набор действий, необходимых произвести ПОСЛЕ завершения процесса мажорного обновления СУБД: \n\
                                       1) необходимо учесть, что файл recovery.conf более не используются в логике работы СУБД (для кластерной конфигурации) \n\
                                       2) в работе АС необходимо учесть, что была расширена информация о клиентских сертификатах ssl в представлении pg_stat_ssl \
                                       и колонка clientdn была переименована в client_dn \n\
                                       3) в работе АС необходимо учесть, что были изменены параметры хранения и ротации WAL-файлов, параметр wal_keep_segments был объявлен \
                                       устаревшим, поэтому необходимо перейти на использование параметра wal_keep_size \n\
                                       4) обращаем внимание, что начиная с версии СУБД Pangolin 5.1.0 введено понятие TRUSTED EXTENSIONS, таким образом определенные \
                                       расширения (список таких расширений можно получить с помощью запроса SELECT DISTINCT name FROM pg_available_extension_versions \
                                       WHERE TRUSTED ORDER BY name;) в дальнейшем могут быть созданы пользователями с правами CREATE (пользователи входящие в as_admin группу) \
                                       на уровне базы данных \n\
                                       5) в работе АС необходимо учесть, что в новой версии СУБД Pangolin могли быть изменены некоторые вендорские процедуры, а именно мог \
                                       измениться состав или порядок аргументов для них (например, функции sec_admin, в которых убран аргумент current_database). \n\
                                       Рекомендация: перед началом обновления версии СУБД необходимо внимательно изучить release notes новой версии.__{{ control_name }}.TODO.AFTER"

update_control_msgs:
  fails:
    update_failed:                    "{{ control_name }}.FAIL__В процессе работы Механизма обновления возникла ошибка.
                                       {% if (is_inner_full_backup and action_type == 'update_major') \
                                             or (action_type == 'update_minor' and handle_update_errors and is_recovery_available) %}\
                                       Было произведено восстановление версии СУБД Pangolin до запуска обновления. \
                                       {% elif action_type == 'update_minor' and not is_recovery_available %}\
                                       Восстановление СУБД для данного типа ошики не доступно. \
                                       {% elif action_type == 'update_minor' and not handle_update_errors %}\
                                       Автоматическое восстановление СУБД отключено. \
                                       {% else %}\
                                       Опция восстановления предыдущей версии СУБД Pangolin не была активирована. \
                                       {% endif %}\
                                       Ознакомьтесь с логами и обратитесь к Администраторам СУБД.__{{ control_name }}.FAIL"
    pg_upgrade_has_error:             "{{ control_name }}.FAIL__Миграция данных с помощью утилиты pg_upgrade завершилась с ошибкой. Обратитесь к администраторам БД для анализа проблемы. \
                                       С ошибками можно ознакомиться на хосте master в директории pg_upgrade_log_link \
                                       {% if is_print_pg_upgrade_logs %}\
                                       или в логе задачи (имя таски: journal pg_upgrade)\
                                       {% endif %}\
                                       .__{{ control_name }}.FAIL"
    pg_receivewal_failed:             "{{ control_name }}.FAIL__Запуск службы накопления WAL pg_receivewal завершился с ошибкой__{{ control_name }}.FAIL"
    pg_probackup_backup_failed:       "{{ control_name }}.FAIL__Не удалось создать локальную резервную копию версии pg_current_version в директории {{ backup.pg_probackup_bak_dir }}/pg_probackup.__{{ control_name }}.FAIL"
    pg_probackup_restore_failed:      "{{ control_name }}.FAIL__Не удалось выполнить восстановление версии {{ pg_current_version }} из локальной резервной копии {{ backup.pg_probackup_bak_dir }}/pg_probackup.__{{ control_name }}.FAIL"
    update_component_pg_fail:         "{{ control_name }}.FAIL__В процессе обновления возникла ошибка при настройке компонента postgresql.__{{ control_name }}.FAIL"
    update_component_patroni_fail:    "{{ control_name }}.FAIL__В процессе обновления возникла ошибка при настройке компонента patroni.__{{ control_name }}.FAIL"
    update_component_pgbouncer_fail:  "{{ control_name }}.FAIL__В процессе обновления возникла ошибка при настройке компонента pgbouncer.__{{ control_name }}.FAIL"
    update_component_haproxy_fail:    "{{ control_name }}.FAIL__В процессе обновления возникла ошибка при настройке компонента HaProxy.__{{ control_name }}.FAIL"
    update_component_config_fail:     "{{ control_name }}.FAIL__В процессе конфигурирования СУБД Pangolin на хосте, выполняющим роль мастера, возникла ошибка.__{{ control_name }}.FAIL"
    update_component_checkup_fail:    "{{ control_name }}.FAIL__В процессе подготовки перед обновлением СУБД Pangolin возникла ошибка.__{{ control_name }}.FAIL"
    update_component_rsyslog_fail:    "{{ control_name }}.FAIL__В процессе настройки rsyslog для СУБД Pangolin возникла ошибка.__{{ control_name }}.FAIL"
    update_component_src_fail:        "{{ control_name }}.FAIL__При восстановлении работоспособности службы СРК возникла неопределенная ситуация. Для понимания на какую директорию должен указывать линк \
                                        /pgarclogs/{{ current_src_manage_backup_sh_file_prefix_name }}, представляющий собой путь по которому СРК ищет бэкапируемые файлы, обратитесь к администраторам СУБД__{{ control_name }}.FAIL"
    stop_pg_auth_reencrypt:           "{{ control_name }}.FAIL__Не удается остановить работающую утилиту перешифрования паролей (pg_auth_reencrypt). \
                                       Обновление не может быть продолжено. Обратитесь к Администраторам СУБД.__{{ control_name }}.FAIL"
    update_component_pg_auth_reencrypt_fail: "{{ control_name }}.FAIL__В процессе обновления возникла ошибка при настройке утилиты перешифрования паролей \
                                              pg_auth_reencrypt.__{{ control_name }}.FAIL"
    update_component_src_status_fail: "{{ control_name }}.FAIL__На текущий момент обновление невозможно так как активна сессия снятия РК. \
                                      Дождитесь окончания снятия РК со стенда__{{ control_name }}.FAIL"
    cluster_name_found:               "{{ control_name }}.FAIL__Укажите актуальное имя кластера в .bash_profile в параметре '- export CLNAME= '__{{ control_name }}.FAIL"
    found_cert:                       "{{ control_name }}.FAIL__Файл сертификата {} не найден__{{ control_name }}.FAIL"
    type_configuration:               "{{ control_name }}.FAIL__В кандидате на обновление обнаружено несоответствие установленных компонент кластера Pangolin \
                                       с текущим типом конфигурации.__{{ control_name }}.FAIL"
  warnings:
    pg_profile_db_update:             "{{ control_name }}.WARNING__Расширение pg_profile будет установлено в БД - 'database'__WARNING.{{ control_name }}"
  debug_info:
    pg_upgrade_time_work:             "{{ control_name }}.PANGOLIN.INFO__Время работы утилиты pg_upgrade заняло pg_upgrade_time_work минут.__{{ control_name }}.PANGOLIN.INFO"
    pg_upgrade_print_log_time_work:   "{{ control_name }}.PANGOLIN.INFO__Распечатка логов работы утилиты pg_upgrade заняло pg_upgrade_print_log_time_work минут.__{{ control_name }}.PANGOLIN.INFO"
    rsync_time_work:                  "{{ control_name }}.PANGOLIN.INFO__Время работы утилиты rsync заняло rsync_time_work минут.__{{ control_name }}.PANGOLIN.INFO"
    rsync_print_log_time_work:        "{{ control_name }}.PANGOLIN.INFO__Распечатка логов работы утилиты rsync заняло rsync_print_log_time_work минут.__{{ control_name }}.PANGOLIN.INFO"
    reindex_time_work:                "{{ control_name }}.PANGOLIN.INFO__Время работы утилиты reindexdb заняло reindex_time_work минут.__{{ control_name }}.PANGOLIN.INFO"
    update_statistic_time_work:       "{{ control_name }}.PANGOLIN.INFO__Время работы утилиты vacuumdb заняло update_statistic_time_work минут.__{{ control_name }}.PANGOLIN.INFO"
    full_backup_db_time_work:         "{{ control_name }}.PANGOLIN.INFO__Время создания полной резервной копии БД заняло full_backup_db_time_work минут.__{{ control_name }}.PANGOLIN.INFO"
    recovery_time_work:               "{{ control_name }}.PANGOLIN.INFO__Время восстановления исходного состояния СУБД заняло recovery_time_work минут.__{{ control_name }}.PANGOLIN.INFO"
  info:
    full_update_time:                 "{{ control_name }}.INFO__Полное время работы скриптов обновления заняло full_update_time минут.__{{ control_name }}.INFO"
    pg_probackup_backup_start:        "{{ control_name }}.INFO__Процесс снятия локальной копии запущен для версии {{ pg_current_version }} в директорию {{ backup.pg_probackup_bak_dir }}/pg_probackup.__{{ control_name }}.INFO"
    pg_probackup_restore_start:       "{{ control_name }}.INFO__Процесс восстановления локальной копии для версии {{ pg_current_version }} из директории {{ backup.pg_probackup_bak_dir }}/pg_probackup запущен.__{{ control_name }}.INFO"
    pg_receivewal_stop:               "{{ control_name }}.INFO__Служба приёма журнала предзаписи pg_receivewal успешно остановлена.__{{ control_name }}.INFO"
    pg_receivewal_ok:                 "{{ control_name }}.INFO__Служба приёма журнала предзаписи pg_receivewal успешно запущена.__{{ control_name }}.INFO"
    pg_probackup_backup_ok:           "{{ control_name }}.INFO__Локальная копия текущей версии {{ pg_current_version }} создана в директории {{ backup.pg_probackup_bak_dir }}/pg_probackup и провалидирована успешно.__{{ control_name }}.INFO"
    pg_probackup_restore_ok:          "{{ control_name }}.INFO__Версия {{ pg_current_version }} успешно восстановлена из локального бекапа.__{{ control_name }}.INFO"
    trigger_update_stop:              "{{ control_name }}.INFO__Началась процедура миграции данных при помощи утилиты pg_upgrade, в следствии чего прервать обновление невозможно.__{{ control_name }}.INFO"
  ok:
    update_successfully:              "{{ control_name }}.OK__Обновление успешно завершено.__{{ control_name }}.OK"
